# _tools/test_acc_data.R -- self-contained check of _tools/acc_data.R (no project data, no real key needed).
# Run from the repo root: Rscript _tools/test_acc_data.R  -> prints "acc_data tests: PASS" or stops.
.t0 <- Sys.time()
source(file.path("_tools", "acc_data.R"))
Sys.setenv(ACC_DATA_KEY = "test-only-key-0123456789abcdefghijklmn", ACC_DEIS_VERSION = "")
w <- file.path(tempfile("acc_test_"), "repo")
dir.create(file.path(w, "_deis"), recursive = TRUE)
dir.create(file.path(w, "src", "enpg", "Informe técnico"), recursive = TRUE)
file.create(file.path(w, ".acc_root"))
old <- setwd(w)
on.exit(setwd(old), add = TRUE)
writeBin(as.raw(sample(0:255, 2e5, TRUE)), file.path("src", "enpg", "Informe técnico", "ñandú (PG).DTA.dta"))
utils::write.csv(data.frame(x = 1:1000), file.path("src", "enpg", "b.csv"), row.names = FALSE)
acc_pack(file.path("src", "enpg"), file.path("_enpg.tar.xz.enc"))
p <- acc_data("_enpg.tar.xz.enc", file.path("Informe técnico", "ñandú (PG).DTA.dta"))
stopifnot(unname(tools::md5sum(p)) == unname(tools::md5sum(file.path("src", "enpg", "Informe técnico", "ñandú (PG).DTA.dta"))))
utils::write.csv(data.frame(x = 1:5), file.path("src", "enpg", "b.csv"), row.names = FALSE)
acc_pack(file.path("src", "enpg"), file.path("_enpg.tar.xz.enc"))
stopifnot(nrow(utils::read.csv(acc_data("_enpg.tar.xz.enc", "b.csv"))) == 5L)  # re-pack refreshes the session copy
b <- readBin("_enpg.tar.xz.enc", "raw", file.size("_enpg.tar.xz.enc"))
b[100] <- xor(b[100], as.raw(1))
writeBin(b, "tampered.tar.xz.enc")
stopifnot(inherits(try(acc_unpack("tampered.tar.xz.enc", tempfile()), silent = TRUE), "try-error"))
stopifnot(inherits(try(acc_unpack("_enpg.tar.xz.enc", tempfile(), key = "wrong"), silent = TRUE), "try-error"))
hdr <- "A\xd1O;FECHA_DEF;SEXO_NOMBRE;EDAD_TIPO;EDAD_CANT;COD_COMUNA;COMUNA"
for (s in c("15092026", "29092026")) {
  csv <- file.path(tempdir(), sprintf("DEFUNCIONES_FUENTE_DEIS_2024_2026_%s.csv", s))
  rows <- c(hdr, "2024;2024-01-02;Hombre;1;40;13110;La Florida", "2024;2024-03-04;Mujer;3;20;5109;Vi\xf1a del Mar")
  if (s == "29092026") rows <- c(rows, "2026;2026-09-20;Mujer;1;80;5109;Vi\xf1a del Mar")
  writeLines(rows, csv, useBytes = TRUE)
  zip <- file.path(w, "_deis", sub("\\.csv$", ".zip", basename(csv)))
  if (requireNamespace("zip", quietly = TRUE)) zip::zip(zip, csv, mode = "cherry-pick") else utils::zip(zip, csv, flags = "-jq")
  acc_deis_update()
}
for (s in c("15102026", "09062026")) file.create(file.path("_deis", sprintf("DEFUNCIONES_FUENTE_DEIS_2024_2026_%s.tar.xz.enc", s)))
stopifnot(basename(acc_latest("_deis")) == "DEFUNCIONES_FUENTE_DEIS_2024_2026_15102026.tar.xz.enc")
unlink(file.path("_deis", sprintf("DEFUNCIONES_FUENTE_DEIS_2024_2026_%s.tar.xz.enc", c("15102026", "09062026"))))
d <- acc_deis()
stopifnot(nrow(d) == 3L, names(d)[1] == "AÑO", d$COMUNA[3] == "Viña del Mar", sum(d$EDAD_TIPO == 1) == 2L)
Sys.setenv(ACC_DEIS_VERSION = "15092026")
stopifnot(nrow(acc_deis()) == 2L)
Sys.setenv(ACC_DEIS_VERSION = "")
source(file.path(old, "_tools", "check_bundles.R"))
message(sprintf("acc_data tests: PASS (%.2f min)", as.numeric(difftime(Sys.time(), .t0, units = "mins"))))
